version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/packages/core"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/lib-node"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/lib-web"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/lib-react-native"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/lib-react-native-jsi"
    schedule:
      interval: "weekly"
