version: 2
updates:
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      # Disable version updates for npm dependencies
    open-pull-requests-limit: 0
  - package-ecosystem: "npm"
    directory: "/packages/core"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/lib-node"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/lib-web"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/lib-react-native"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/packages/lib-react-native-jsi"
    schedule:
      interval: "weekly"
