[package]
name = "tonos_client_react_native_android"
version = "1.1.0"
authors = ["TON Labs"]
license = "Apache-2.0"

[lib]
name = "tonosclient"
crate-type = ["staticlib"]

[dependencies]
libc = "0.2"
jni = { version = "0.12.0", optional = true, default-features = false }
ton_client = { git = "https://github.com/tonlabs/TON-SDK.git" }

[profile.release]
lto = true
